## Building Machine Learning Models

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as pt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)

### Importing ml algorithms

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression as lg
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.neighbors import KNeighborsClassifier as knc
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import GradientBoostingClassifier as gbc
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

In [7]:
from sklearn.metrics import classification_report as cr
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import accuracy_score as acs

In [8]:
df=pd.read_csv("emp_normalized.csv")

In [9]:
df

Age  Attrition  DailyRate  DistanceFromHome  Education  \
0       0.952381        0.0   0.071429          0.244898       1.00   
1       0.404762        0.0   0.436429          0.551020       0.75   
2       0.452381        0.0   0.697857          0.306122       1.00   
3       0.380952        1.0   0.785000          0.183673       0.25   
4       0.714286        0.0   0.060000          0.673469       0.50   
...          ...        ...        ...               ...        ...   
546216  0.047619        0.0   0.980000          0.816327       0.50   
546217  1.000000        1.0   0.850000          0.163265       1.00   
546218  0.785714        0.0   0.832143          1.000000       0.50   
546219  0.880952        0.0   0.855714          0.653061       1.00   
546220  0.619048        1.0   0.689286          0.673469       0.50   

        EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel  \
0                      0.000000    0.017647        1.000000      1.00   
1                      0.666667    0.352941        0.000000      1.00   
2                      0.666667    0.658824        0.333333      0.50   
3                      0.333333    0.982353        0.333333      0.00   
4                      0.666667    0.547059        0.000000      0.50   
...                         ...         ...             ...       ...   
546216                 0.000000    1.000000        0.666667      0.75   
546217                 0.666667    0.858824        1.000000      0.50   
546218                 1.000000    0.729412        0.333333      0.50   
546219                 0.000000    0.658824        0.000000      0.50   
546220                 1.000000    0.423529        0.333333      0.00   

        JobSatisfaction  MonthlyIncome  NumCompaniesWorked  PercentSalaryHike  \
0              1.000000       0.325767               0.750           0.693878   
1              0.000000       0.800016               0.750           0.959184   
2              0.333333       0.551831               0.375           0.448980   
3              1.000000       0.439369               0.250           0.040816   
4              0.000000       0.310546               0.125           0.285714   
...                 ...            ...                 ...                ...   
546216         1.000000       0.072541               1.000           0.224490   
546217         0.000000       0.496470               0.000           0.326531   
546218         0.000000       0.223164               0.000           0.040816   
546219         0.666667       0.375808               0.625           0.530612   
546220         0.666667       0.174723               0.875           0.510204   

        PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
0                0.333333                  0.333333          1.000000   
1                1.000000                  1.000000          0.666667   
2                0.666667                  0.666667          0.333333   
3                0.000000                  1.000000          0.000000   
4                0.333333                  1.000000          0.333333   
...                   ...                       ...               ...   
546216           0.000000                  0.000000          0.000000   
546217           0.666667                  0.000000          0.000000   
546218           0.666667                  0.666667          1.000000   
546219           0.666667                  1.000000          0.000000   
546220           0.666667                  0.666667          1.000000   

        TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                1.000000                    0.4         1.000000   
1                0.000000                    0.0         1.000000   
2                0.128205                    0.0         0.000000   
3                0.153846                    0.6         0.666667   
4                0.410256                    1.0         0.333333   
...                

In [10]:
df["Attrition"].unique()

array([0., 1.])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546221 entries, 0 to 546220
Data columns (total 46 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Age                                546221 non-null  float64
 1   Attrition                          546221 non-null  float64
 2   DailyRate                          546221 non-null  float64
 3   DistanceFromHome                   546221 non-null  float64
 4   Education                          546221 non-null  float64
 5   EnvironmentSatisfaction            546221 non-null  float64
 6   HourlyRate                         546221 non-null  float64
 7   JobInvolvement                     546221 non-null  float64
 8   JobLevel                           546221 non-null  float64
 9   JobSatisfaction                    546221 non-null  float64
 10  MonthlyIncome                      546221 non-null  float64
 11  NumCompaniesWorked                 5462

In [8]:
df.columns

Index(['Age', 'Attrition', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'Department_Software', 'Department_Support',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Male',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing D

In [11]:
x=df.drop("Attrition",axis=1)
y=df["Attrition"]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# Training the ml models 

## Logistic Regression

In [11]:
model=lg().fit(x_train,y_train)
p=model.predict(x_test)
p

array([0., 0., 1., ..., 0., 1., 1.])

In [12]:
print("Accuracy:",acs(y_test,p))
print("------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p))
print("------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p))

Accuracy: 0.5001327291866905
------------------------------------------------------------
confusion_matrix:
 [[28143 26410]
 [28198 26494]]
------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.52      0.51     54553
         1.0       0.50      0.48      0.49     54692

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## Decision tree

In [12]:
dtc1 = DecisionTreeClassifier()
dtc1.fit(x_train, y_train)
print("DecisionTreeClassifier")
p1=dtc1.predict(x_test)
p1

DecisionTreeClassifier


array([1., 1., 0., ..., 0., 0., 1.])

In [13]:
print("Accuracy:",acs(y_test,p1))
print("------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p1))
print("------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p1))

Accuracy: 0.5018078630600943
------------------------------------------------------------
confusion_matrix:
 [[27485 27057]
 [27368 27335]]
------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.50      0.50     54542
         1.0       0.50      0.50      0.50     54703

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## Random Forest Classifier

In [13]:
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)  

#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [14]:
print("Accuracy:",acs(y_test,y_pred))
print("------------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,y_pred))
print("------------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,y_pred))

Accuracy: 0.5044441393198773
------------------------------------------------------------------
confusion_matrix:
 [[34321 20232]
 [33905 20787]]
------------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.63      0.56     54553
         1.0       0.51      0.38      0.43     54692

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



In [15]:
import pickle
pickle_out = open('rfc.pkl',"wb")
pickle.dump(classifier,pickle_out)
pickle_out.close()

## KNeighbors Classifier

In [16]:
model5=knc().fit(x_train,y_train)

p5=model5.predict(x_test)

In [17]:
print("Accuracy:",acs(y_test,p5))
print("---------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p5))
print("---------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p5))

Accuracy: 0.5007002608815049
---------------------------------------------------------------
confusion_matrix:
 [[27306 27236]
 [27310 27393]]
---------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.50      0.50     54542
         1.0       0.50      0.50      0.50     54703

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## xgboost

In [18]:
import xgboost as xgb

In [19]:
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(x_train,y_train)

[11:42:09] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [20]:
predictions = xgb_classifier.predict(x_test)

In [21]:
print("Accuracy:",acs(y_test,predictions))
print("---------------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,predictions))
print("---------------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,predictions))

Accuracy: 0.5024303171769875
---------------------------------------------------------------------
confusion_matrix:
 [[27442 27100]
 [27257 27446]]
---------------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.50      0.50     54542
         1.0       0.50      0.50      0.50     54703

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## Naive Bayes

In [23]:
gnb=GaussianNB()
model6=gnb.fit(x_train, y_train,sample_weight=100)  
p6=model6.predict(x_test)

In [24]:
print("Accuracy:",acs(y_test,p6))
print("----------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p6))
print("----------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p6))

Accuracy: 0.5014417135795689
----------------------------------------------------------------
confusion_matrix:
 [[23962 30580]
 [23885 30818]]
----------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.44      0.47     54542
         1.0       0.50      0.56      0.53     54703

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## Gradient Boosting Classifier

In [25]:
model8=gbc().fit(x_train,y_train)
p8=model8.predict(x_test)

In [26]:
print("Accuracy:",acs(y_test,p8))
print("--------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p8))
print("--------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p8))

Accuracy: 0.4992356629594032
--------------------------------------------------------
confusion_matrix:
 [[28865 25677]
 [29029 25674]]
--------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.50      0.53      0.51     54542
         1.0       0.50      0.47      0.48     54703

    accuracy                           0.50    109245
   macro avg       0.50      0.50      0.50    109245
weighted avg       0.50      0.50      0.50    109245



## CatBoost Classifier

In [16]:
clf2 = CatBoostClassifier(
    iterations=100000, 
    learning_rate=0.1, 
    #loss_function='CrossEntropy'
)


clf2.fit(x_train, y_train, verbose=False)

print('CatBoost model is fitted: ' + str(clf2.is_fitted()))
print('CatBoost model parameters:')
print(clf2.get_params())
p11=clf2.predict(x_test)

CatBoost model is fitted: True
CatBoost model parameters:
{'iterations': 100000, 'learning_rate': 0.1}


In [17]:
print("Accuracy:",acs(y_test,p11))
print("--------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,p11))
print("--------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,p11))

Accuracy: 0.647187514302714
--------------------------------------------------------
confusion_matrix:
 [[35190 19363]
 [19180 35512]]
--------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.65      0.65      0.65     54553
         1.0       0.65      0.65      0.65     54692

    accuracy                           0.65    109245
   macro avg       0.65      0.65      0.65    109245
weighted avg       0.65      0.65      0.65    109245



## Light gbm

In [13]:
%%time

from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(boosting_type='gbdt',
    num_leaves=5000,
    max_depth=-1,
    learning_rate=0.1,
    n_estimators=5000,
    subsample_for_bin=200000,
    objective='binary',
    
    min_child_samples=5000,

    reg_alpha=0.9,
    reg_lambda=0.9,
metric='binary_logloss', #metric for binary classification
    
    n_jobs=-1,
    silent=True,
    importance_type='',
    random_state=6)

lgbm.fit(x_train, y_train)
y_pred = lgbm.predict(x_test)

Wall time: 10min 14s


In [14]:
print("Accuracy:",acs(y_test,y_pred))
print("-------------------------------------------------------------")
print("confusion_matrix:\n",cm(y_test,y_pred))
print("-------------------------------------------------------------")
print("classifiction_report:\n",cr(y_test,y_pred))

Accuracy: 0.684845988374754
-------------------------------------------------------------
confusion_matrix:
 [[37435 17444]
 [16985 37381]]
-------------------------------------------------------------
classifiction_report:
               precision    recall  f1-score   support

         0.0       0.69      0.68      0.69     54879
         1.0       0.68      0.69      0.68     54366

    accuracy                           0.68    109245
   macro avg       0.68      0.68      0.68    109245
weighted avg       0.68      0.68      0.68    109245



### As Lightgbm got the highest accuracy among the models so we are using this model for deployement.

In [17]:
lgbm.booster_.save_model("lgbm1.json")